version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: lio
      POSTGRES_PASSWORD: lio
      POSTGRES_DB: lio
    volumes: [db:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://lio:lio@db:5432/lio
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on: [db]
    ports: ["3000:3000"]

  frontend:
    build: ./frontend
    ports: ["5173:80"]
    depends_on: [backend]

volumes:
  db:
